### PR TITLE
Add supported languages with aliases

### PR DESCRIPTION
**Pull request by kuba--**
Signed-off-by: kuba-- <kuba@sourced.tech>
Closes https://github.com/bblfsh/python-client/issues/168

This PR adds basic API changes (new methods) from `v4` branch:
- Supported Languages with Aliases (v2): `def supported_language_manifests()`
- Server Version (v2) `def server_version()`

---
This change is [Reviewable](https://reviewable.io/reviews/bblfsh/python-client/196)

### CODE REVIEW

**Comment by kuba--** [comment]
I believe, we can merge it and push a new release for ml-team.

**Comment by kuba--** [comment]
There is still support for version and supported languages over v1. The new v2 functions are:
`server-version` and `supported_language_manifests`.
But of course we can document which function(s) require which bblfshd version. 
So far (what I don't like) there is no distinction between api v1 and v2, e.g.: `parse` goes over `v2`, but `version` over `v1`, ...

**Comment by ncordon** [comment]
___
*[bblfsh/client.py, line 14 at r2](https://reviewable.io/reviews/bblfsh/python-client/196#-LryInFo1n9ud5pP3j-I:-LryInFp2h_DPuEmlTZl:bhbqskj) ([raw file](https://github.com/bblfsh/python-client/blob/4c8415fe7ebf2d9545393fd58b237ea9dee57f11/bblfsh/client.py#L14)):*
> ```Python
>     VersionRequestV2,
>     SupportedLanguagesRequest,
>     SupportedLanguagesRequestV2,
> ```

Should `SupportedLanguagesResponseV2` be here also?

**Comment by ncordon** [comment]
:lgtm:

**Pull request merged**
